// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POC.Infra.Persistence;

#nullable disable

namespace POC.Infra.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POC.Domain.Entities.Initialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<int>("Status")
                        .HasColumnType("int");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("Initializations", (string)null);
                });

            modelBuilder.Entity("POC.Infra.Persistence.Entities.OutboxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");
                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");
                    b.Property<int>("Attempts")
                        .HasColumnType("int");
                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");
                    b.Property<Guid?>("LockId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("ProcessedAt", "LockedUntil");
                    b.ToTable("Outbox", (string)null);
                });

            modelBuilder.Entity("POC.Infra.Persistence.Entities.ReceivedEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("ReceivedEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
